version: '3.8'

services:
  api:
    container_name: brain-farmer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: sh -c "npm ci && npm run build && npm run start:prod"

  postgres:
    container_name: brain-farmer-db
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
