export const RURAL_PRODUCER_REPOSITORY = Symbol('RURAL_PRODUCER_REPOSITORY');
export const FARM_REPOSITORY = Symbol('FARM_REPOSITORY');
export const CROP_REPOSITORY = Symbol('CROP_REPOSITORY');
export const HARVEST_REPOSITORY = Symbol('HARVEST_REPOSITORY');
